---
displayName: TOPPERS ATK2 SC1 ZCU102
description: TOPPERS ATK2 SC1 ZCU102
tags: ["TOPPERS", "ATK2", "Athrill", "ZCU102"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2674Mi

